services:
  watchyourlan:
    image: aceberg/watchyourlan
    network_mode: "host"      
    restart: unless-stopped
    volumes:
    - ./data:/data/WatchYourLAN
    environment:
      TZ: <TIMEZONE>
      IFACES: "<INTERFACES>"