services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrail
      POSTGRES_PASSWORD: <DBPASSWORD>
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airtrail -d airtrail"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    environment:
      - ORIGIN=http://<HOSTNAME>:3000
      - DB_URL=postgres://airtrail:<DBPASSWORD>@db:5432/airtrail
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
