services:
  redis:
    image: redis:<VERSION>
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save <SECONDS> 1 --loglevel warning --requirepass <PASSWORD>
    volumes: 
      - ./data:/data